import { Member } from "@/types";

const members: Member[] = [
  {
    id: "1",
    name: "리코",
    fans: 0,
    stamina: 100,
    vocal: 80,
    dance: 50,
    visual: 60,
    producing: 40,
    composition: 50,
    balance: 0,
    focus: 50,
    sensitivity: 50,
    intelligence: 50,
    coverSongs: 0,
    originalSongs: 0,
    reaction: 0,
    expression: 0,
  },
  {
    id: "2",
    name: "유니",
    fans: 0,
    stamina: 100,
    vocal: 60,
    dance: 65,
    visual: 55,
    producing: 50,
    composition: 40,
    balance: 0,
    focus: 50,
    sensitivity: 50,
    intelligence: 50,
    coverSongs: 0,
    originalSongs: 0,
    reaction: 0,
    expression: 0,
  },
  {
    id: "3",
    name: "히나",
    fans: 0,
    stamina: 100,
    vocal: 50,
    dance: 50,
    visual: 75,
    producing: 40,
    composition: 45,
    balance: 0,
    focus: 50,
    sensitivity: 50,
    intelligence: 50,
    coverSongs: 0,
    originalSongs: 0,
    reaction: 0,
    expression: 0,
  },
  {
    id: "4",
    name: "마시로",
    fans: 0,
    stamina: 100,
    vocal: 55,
    dance: 45,
    visual: 65,
    producing: 50,
    composition: 60,
    balance: 0,
    focus: 50,
    sensitivity: 50,
    intelligence: 50,
    coverSongs: 0,
    originalSongs: 0,
    reaction: 0,
    expression: 0,
  },
  {
    id: "5",
    name: "타비",
    fans: 0,
    stamina: 100,
    vocal: 65,
    dance: 60,
    visual: 50,
    producing: 40,
    composition: 55,
    balance: 0,
    focus: 50,
    sensitivity: 50,
    intelligence: 50,
    coverSongs: 0,
    originalSongs: 0,
    reaction: 0,
    expression: 0,
  },
  {
    id: "6",
    name: "리제",
    fans: 0,
    stamina: 100,
    vocal: 50,
    dance: 60,
    visual: 70,
    producing: 50,
    composition: 40,
    balance: 0,
    focus: 50,
    sensitivity: 50,
    intelligence: 50,
    coverSongs: 0,
    originalSongs: 0,
    reaction: 0,
    expression: 0,
  },
  {
    id: "7",
    name: "시부키",
    fans: 0,
    stamina: 100,
    vocal: 50,
    dance: 55,
    visual: 50,
    producing: 70,
    composition: 65,
    balance: 0,
    focus: 50,
    sensitivity: 50,
    intelligence: 50,
    coverSongs: 0,
    originalSongs: 0,
    reaction: 0,
    expression: 0,
  },
  {
    id: "8",
    name: "린",
    fans: 0,
    stamina: 100,
    vocal: 50,
    dance: 50,
    visual: 60,
    producing: 60,
    composition: 75,
    balance: 0,
    focus: 50,
    sensitivity: 50,
    intelligence: 50,
    coverSongs: 0,
    originalSongs: 0,
    reaction: 0,
    expression: 0,
  },
  {
    id: "9",
    name: "나나",
    fans: 0,
    stamina: 100,
    vocal: 55,
    dance: 50,
    visual: 55,
    producing: 75,
    composition: 50,
    balance: 0,
    focus: 50,
    sensitivity: 50,
    intelligence: 50,
    coverSongs: 0,
    originalSongs: 0,
    reaction: 0,
    expression: 0,
  },
];

export default members;
